adding ability to query remote hosts using SSH

diff --git a/neofetch b/neofetch
--- a/neofetch
+++ b/neofetch
@@ -4466,6 +4466,10 @@ OTHER:
     -v                          Display error messages.
     -vv                         Display a verbose log for error reporting.
 
+SSH:
+    --ssh HOST                  Run neofetch on remote host using SSH. All arguments except
+                                --ssh are passed to remote system. Can be chained to jump.
+
 DEVELOPER:
     --gen-man                   Generate a manpage for Neofetch in your PWD. (Requires GNU help2man)
 
@@ -4652,6 +4656,16 @@ get_args() {
                 help2man -n "A fast, highly customizable system info script" \
                           -N ./neofetch -o neofetch.1
                 exit 1
+            ;;
+
+            "--ssh")
+                ssh_mode="yes"
+                if [ "x$ssh_host" == "x" ]
+                then
+                    ssh_host="$2"
+                fi
+                shift
+                shift
             ;;
 
             "--json")
@@ -8823,6 +8837,60 @@ EOF
     fi
 }
 
+ssh_mode(){
+    # safely pass arguments to remote system
+
+    ssh_arg=no
+    newargs=""
+    while [[ "$1" ]]
+    do
+        if [ "$ssh_arg" == "no" -a "$1" == "--ssh" ]
+        then
+            shift
+            shift
+            ssh_arg=yes
+            continue
+        fi
+        newarg="$( echo "$1" | base64 -w 0 )"
+        # FIXME this will fail when echo consumes an option (-n,-e,-E) not intented for it
+
+        newargs="$newargs $newarg"
+        shift
+    done
+
+    # generate random filename and payload and pipe it to ssh
+
+    REMOTE_SCRIPT=/tmp/neofetch-$( head -c 14 /dev/urandom | xxd -ps ).sh
+    BOUNDARY="_THE_END_OF_FILE_"
+    (
+        echo "base64 -d > $REMOTE_SCRIPT <<$BOUNDARY"
+        base64 < "$BASH_SOURCE"
+        echo "$BOUNDARY"
+        echo -n "bash $REMOTE_SCRIPT "
+
+        # safely decode base64 and encode quotes
+
+        for newarg in $newargs
+        do
+            echo -n "'""$( echo "$newarg" | base64 -d | sed -e "sx'x'\"'\"'xg" )""' "
+        done
+        echo ""
+
+        echo "rm -f $REMOTE_SCRIPT"
+
+    ) | ssh -t "$ssh_host" "sh" 2> /dev/null
+
+    ssh_err="$?"
+    if [ "$ssh_err" -ne "0" ]
+    then
+        echo "SSH from $HOSTNAME to $ssh_host failed with exit code: $ssh_err"
+        exit "$ssh_err"
+    fi
+
+    exit
+
+}
+
 main() {
     cache_uname
     get_os
@@ -8832,6 +8900,9 @@ main() {
 
     get_args "$@"
     get_simple "$@"
+
+    [ "$ssh_mode" == "yes" ] && ssh_mode "$@"
+
     [[ "$verbose" != "on" ]] && exec 2>/dev/null
     get_distro
     get_bold
